/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'team-members': TeamMember;
    'gallery-images': GalleryImage;
    testimonials: Testimonial;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'gallery-images': GalleryImagesSelect<false> | GalleryImagesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'start-page': StartPage;
  };
  globalsSelect: {
    'start-page': StartPageSelect<false> | StartPageSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Beschreibung des Bildes für Barrierefreiheit und SEO
   */
  alt: string;
  /**
   * Base64-kodiertes Vorschaubild (automatisch generiert)
   */
  blurDataURL?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  description: string;
  /**
   * Mehrere Fotos hochladen. Das erste Foto wird standardmäßig angezeigt. Bei Hover werden die Fotos basierend auf Cursor-Bewegung gewechselt.
   */
  photos: (number | Media)[];
  /**
   * Niedrigere Zahlen werden zuerst angezeigt
   */
  sortOrder?: number | null;
  /**
   * Nur aktive Teammitglieder werden auf der Website angezeigt
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images".
 */
export interface GalleryImage {
  id: number;
  title: string;
  image: number | Media;
  /**
   * Niedrigere Zahlen werden zuerst angezeigt
   */
  sortOrder?: number | null;
  /**
   * Hervorgehobene Bilder werden größer in der Galerie dargestellt
   */
  isFeatured?: boolean | null;
  /**
   * Nur aktive Bilder werden in der Galerie angezeigt
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  text: string;
  author: string;
  /**
   * Profilbild des Autors
   */
  image?: (number | null) | Media;
  /**
   * Bewertung von 0 bis 5 Sternen (Dezimalzahlen erlaubt, z.B. 4.5)
   */
  rating: number;
  /**
   * Datum, an dem die Bewertung abgegeben wurde (nicht das Erstellungsdatum des Eintrags)
   */
  reviewDate: string;
  /**
   * Niedrigere Zahlen werden zuerst angezeigt
   */
  sortOrder?: number | null;
  /**
   * Nur aktive Testimonials werden auf der Website angezeigt
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'gallery-images';
        value: number | GalleryImage;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blurDataURL?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  description?: T;
  photos?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images_select".
 */
export interface GalleryImagesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  sortOrder?: T;
  isFeatured?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  text?: T;
  author?: T;
  image?: T;
  rating?: T;
  reviewDate?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Autorenansicht für die Startseite mit frei sortierbaren Inhaltsblöcken.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "start-page".
 */
export interface StartPage {
  id: number;
  header?:
    | {
        practiceName: string;
        phone: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'navigation';
      }[]
    | null;
  layout?:
    | (
        | {
            headline: string;
            subheadline: string;
            description: string;
            heroImage?: (number | null) | Media;
            ctaPrimaryText: string;
            ctaPrimaryHref: string;
            ctaSecondaryText: string;
            ctaSecondaryHref: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow: string;
            headline: string;
            groups: {
              category: string;
              items: {
                text: string;
                id?: string | null;
              }[];
              id?: string | null;
            }[];
            ctaText: string;
            ctaButtonLabel: string;
            ctaButtonHref: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            text: string;
            /**
             * Wählen Sie ein Teammitglied als Autor des Zitats aus
             */
            author?: (number | null) | TeamMember;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            eyebrow: string;
            headline: string;
            description: string;
            googleReviewUrl: string;
            reviewCount: number;
            averageRating: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            eyebrow: string;
            headline: string;
            description: string;
            emptyStateText: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            eyebrow: string;
            headline: string;
            description: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team';
          }
        | {
            eyebrow: string;
            headline: string;
            description: string;
            openingHours?:
              | {
                  day: string;
                  state: 'open' | 'reservation' | 'closed';
                  times: string;
                  id?: string | null;
                }[]
              | null;
            emergency: {
              title: string;
              description: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hours';
          }
        | {
            eyebrow: string;
            headline: string;
            description: string;
            address: {
              street: string;
              city: string;
              additional?: string | null;
            };
            phone: string;
            email: string;
            consultationTimes: string;
            directionsDescription: string;
            directionsLinkLabel: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
        | {
            eyebrow: string;
            headline: string;
            description: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
      )[]
    | null;
  footer?:
    | {
        tagline: string;
        copyright: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'footer';
      }[]
    | null;
  seo: {
    title: string;
    description: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "start-page_select".
 */
export interface StartPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        navigation?:
          | T
          | {
              practiceName?: T;
              phone?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              description?: T;
              heroImage?: T;
              ctaPrimaryText?: T;
              ctaPrimaryHref?: T;
              ctaSecondaryText?: T;
              ctaSecondaryHref?: T;
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              groups?:
                | T
                | {
                    category?: T;
                    items?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              ctaText?: T;
              ctaButtonLabel?: T;
              ctaButtonHref?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              author?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              description?: T;
              googleReviewUrl?: T;
              reviewCount?: T;
              averageRating?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              description?: T;
              emptyStateText?: T;
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        hours?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              description?: T;
              openingHours?:
                | T
                | {
                    day?: T;
                    state?: T;
                    times?: T;
                    id?: T;
                  };
              emergency?:
                | T
                | {
                    title?: T;
                    description?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              description?: T;
              address?:
                | T
                | {
                    street?: T;
                    city?: T;
                    additional?: T;
                  };
              phone?: T;
              email?: T;
              consultationTimes?: T;
              directionsDescription?: T;
              directionsLinkLabel?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
      };
  footer?:
    | T
    | {
        footer?:
          | T
          | {
              tagline?: T;
              copyright?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}